<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<!DOCTYPE html>
<html>
<head>
<title>Availability Form</title>
<link rel="stylesheet"
	href="${pageContext.request.contextPath}/css/styles.css"
	type="text/css">
<link rel="stylesheet"
	href="${pageContext.request.contextPath}/css/select.css"
	type="text/css">
<meta charset="ISO-8859-1">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet"
	href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
	$(function () {
    	$('#datepicker').datepicker();
    });	
</script>

</head>
<body>
	<%@page import="java.util.*"%>

	<img src="${pageContext.request.contextPath}/images/statCover.png"
		alt="STATCover Logo"
		style="float: center; width: 600px; height: 200px;">
	<br>
	<br>
	<a href="${pageContext.request.contextPath}/jsps/home.jsp">Home</a>
	<br>
	<br>

	<h3>Please complete your request details</h3>
	
	<!--Show the message if any -->
	<label style="color: red">${message}</label>

	<!--Remove the message. We should do this otherwise the last message always appears on the page -->
	<%
		request.setAttribute("message", null);
	%>
	
	<form id="availability" method="post"
		action="${pageContext.request.contextPath}/StatcoverServlets.Availability_Insert">

		<fieldset class="field-set">
			<legend>Availability Details</legend>

			<div class="field-group">
				<!-- Availability ID is autogenerated -->
				<label for="availid">Availability ID:</label> <input type="text"
					name="availid" id="availid" size="5" maxlength="12"
					placeholder="--Leave this availability id empty--" disabled />
			</div>

			<div class="field-group">
				<!-- Staff ID should not be empty and should be numeric only -->
				<label for="staffid">Staff ID:</label> <input type="text"
					name="staffid" id="staffid" size="5" maxlength="12"
					value="${staffid}" readonly />
			</div>

			<div class="field-group">
				<!-- First name should not be empty and should be a string not a number -->
				<label for="firstname">First name:</label> <input type="text"
					name="firstname" id="firstname" size="10" maxlength="40"
					value="${staffName}" readonly />
			</div>

			<div class="field-group">
				<!-- Last name should not be empty and should be a string not a number -->
				<label for="lastname">Last Name:</label> <input type="text"
					name="lastname" id="lastname" size="10" maxlength="40"
					value="${staffLname}" readonly />
			</div>

			<div class="field-group">
				<!-- License number should not be empty and should be numeric -->
				<label for="licenseNum">License Number:</label> <input type="text"
					name="licenseNum" id="licenseNum" size="20" maxlength="50"
					value="${staffLicense}" readonly />
			</div>

			<div class="field-group">
				<!-- Shift date should not be empty and should be a valid date  -->
				<label for="datepicker">Availability Date:</label> <input
					type="text" name="availDate" id="datepicker"
					placeholder=" MM/DD/YYYY" required>
			</div>

			<div class="field-group">
				<!-- Choose one shift from the list -->
				<label for="shift">Preferred Shift:</label> <select id="shift"
					name="shift" required>
					<option value="">Select One</option>
					<option value="AM">AM</option>
					<option value="M">M</option>
					<option value="PM">PM</option>
					<option value="T">T</option>
					<option value="N">N</option>
				</select>
			</div>

		</fieldset>

		<input type="submit" value="Submit" />
	</form>


</body>
</html>