<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<!DOCTYPE html>
<html>
<head>
<title>Registration Form</title>
<link rel="stylesheet"
	href="${pageContext.request.contextPath}/css/styles.css"
	type="text/css">
<link rel="stylesheet"
	href="${pageContext.request.contextPath}/css/radio.css"
	type="text/css">
<link rel="stylesheet"
	href="${pageContext.request.contextPath}/css/select.css"
	type="text/css">
<meta charset="ISO-8859-1">
</head>
<body>

	<img src="${pageContext.request.contextPath}/images/statCover.png"
		alt="STATCover Logo"
		style="float: center; width: 600px; height: 200px;">
	<br>
	<br>
	<a href="${pageContext.request.contextPath}/jsps/home.jsp">Home</a>
	<br>
	<br>

	<h3>Please complete your details</h3>
	
	<!--Show the message if any -->
	<label style="color: red">${message}</label>

	<!--Remove the message. We should do this otherwise the last message always appears on the page -->
	<%
		request.setAttribute("message", null);
	%>

	<form id="registration" method="post"
		action="${pageContext.request.contextPath}/StatcoverServlets.Registration_Insert">

		<fieldset class="field-set">
			<legend>Registration Details</legend>

			<div class="field-group">
				<!-- Registration ID is autogenerated -->
				<label for="regid">Registration ID:</label> <input type="text"
					name="regid" id="regid" size="5" maxlength="12"
					placeholder="--Leave this registration id empty--" disabled />
			</div>

			<div class="field-group">
				<!-- First name should not be empty and should be a string not a number -->
				<label for="firstname">First name:</label> <input type="text"
					name="firstname" id="firstname" size="10" maxlength="40"
					required="required" pattern="[A-Za-z]{2,}"
					title="two or more alphabets only"
					placeholder="--Please enter first name--" />
			</div>

			<div class="field-group">
				<!-- Last name should not be empty and should be a string not a number -->
				<label for="lastname">Last Name:</label> <input type="text"
					name="lastname" id="lastname" size="10" maxlength="40"
					required="required" pattern="[A-Za-z]{2,}"
					title="two or more alphabets only"
					placeholder="--Please enter last name--" />
			</div>

			<div class="field-group">
				<!-- Choose one from the options provided -->
				<label for="gender">Gender:</label> 
				<input type="radio" id="male" name="gender" value="M" checked><label for="male">Male</label>
				<input type="radio" id="female" name="gender" value="F" ><label for="female">Female</label>
			</div>

			<div class="field-group">
				<!-- Email should not be empty and should contain at least one @ -->
				<label for="email">Email:</label> <input type="text" name="email"
					id="email" size="10" maxlength="40" required="required"
					pattern="^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$"
					title="Valid email address only, must contain at least one @ and .com"
					placeholder="--Please enter email--" />
			</div>

			<div class="field-group">
				<!-- Contact number should not be empty and contain numeric only -->
				<label for="contactNum">Contact Number:</label> <input type="text"
					name="contactNum" id="contactNum" size="7" maxlength="12"
					required="required" pattern="(^[0][2][12579]{1})(\d{6,7}$)"
					title="valid contact numbers only"
					placeholder="--Please enter contact number--" />
			</div>

			<div class="field-group">
				<!-- Address should not be empty and should be Alphanumeric -->
				<label for="address">Address:</label> <input type="text"
					name="address" id="address" size="20" maxlength="50"
					placeholder="--Please enter address--" required />
			</div>

			<br>

			<div class="field-group">
				<!-- Choose one specialty from the list -->
				<label for="specialty">Specialty:</label> <select required
					id="specialty" name=specialty>
					<option value="">Select One</option>
					<option value="ED">ED</option>
					<option value="General">General</option>
					<option value="Medical">Medical</option>
					<option value="Surgical">Surgical</option>
					<option value="Maternity N">Maternity North</option>
					<option value="Maternity S">Maternity South</option>
					<option value="Gastro">Gastro</option>
					<option value="Birthing Unit">Birthing Unit</option>
				</select>
			</div>

			<br>

			<div class="field-group">
				<!-- Choose one position from the list -->
				<label for="position">Position:</label> <select required
					id="position" name="position">
					<option value="">Select One</option>
					<option value="RN">RN</option>
					<option value="HCA">HCA</option>
				</select>
			</div>

			<br>

			<div class="field-group">
				<!-- Years of experience should not be empty and should be numeric -->
				<label for="yearsofex">Years of Experience:</label> <input
					type="text" name="yearsofex" id="yearsofex" size="5" maxlength="10"
					pattern="[0-9]{1,2}" title="Valid numbers only"
					placeholder="--Please enter years of experience--" />
			</div>

		</fieldset>

		<input type="submit" value="Submit" />
	</form>

</body>
</html>