<%@page import="utils.GlobalUtils"%>
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>


<!DOCTYPE html>
<html>
<head>
<title>Request Form</title>
<link rel="stylesheet"
	href="${pageContext.request.contextPath}/css/styles.css"
	type="text/css">
<link rel="stylesheet"
	href="${pageContext.request.contextPath}/css/select.css"
	type="text/css">
<meta charset="ISO-8859-1">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet"
	href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
	$(function () {
    	$('#datepicker').datepicker();
    	
    	$('#shift').change(function() {
    		val=$('#shift').val();
    		//alert(val);
    		switch(val) {
    		  case "AM":
       		   		$('#timefrom').val("07:00"); 
    		   		$('#timeto').val("15:00");
    		    break;
    		  case "PM":
   		   			$('#timefrom').val("15:00"); 
   		   			$('#timeto').val("23:00");
    		    break;
    		  case "N":
       		   		$('#timefrom').val("23:00"); 
    		   		$('#timeto').val("07:00");
  		    		break;
  		  		case "M":
         		   	$('#timefrom').val("07:00"); 
        		   	$('#timeto').val("19:00");
  		    		break;  
  		  		case "T":
         		   	$('#timefrom').val("19:00"); 
        		   	$('#timeto').val("07:00");
		    		break;    		    	
    		  default:
    		    // code block
    		} 
    	});
    });
</script>

<script>
function validate() {
	var selectBox = document.getElementById('position');
	var userInput = selectBox.options[selectBox.selectedIndex].value;
	if (userInput == 'RN') {
		if (document.getElementById('specialty').value == "") {
			alert('All fields are require.');
			return false;
		}
	}
}
</script>

</head>
<body>
	<%@page import="utils.GlobalUtils"%>;
	
	<img src="${pageContext.request.contextPath}/images/statCover.png"
		alt="STATCover Logo"
		style="float: center; width: 600px; height: 200px;">
	<br>
	<br>
	<a href="${pageContext.request.contextPath}/jsps/home.jsp">Home</a>
	<br>
	<br>

	<h3>Please complete your request details</h3>
	
	<!--Show the message if any -->
	<label style="color: red">${message}</label>

	<!--Remove the message. We should do this otherwise the last message always appears on the page -->
	<%
		request.setAttribute("message", null);
	%>
	
	<form id="request" method="post" action="${pageContext.request.contextPath}/StatcoverServlets.Request_Insert">

		<fieldset class="field-set">
			<legend>Request Details</legend>

			<div class="field-group">
				<!-- Request ID is autogenerated -->
				<label for="reqid">Request ID:</label> <input type="text"
					name="reqid" id="reqid" size="5" maxlength="12"
					placeholder="--Leave this request id empty--" disabled />
			</div>

			<div class="field-group">
				<!-- Choose one position from the list -->
				<label for="position">Position:</label> <select id="position"
					name="position" required>
					<option value="">Select One</option>
					<option value="RN">RN</option>
					<option value="HCA">HCA</option>
				</select>
			</div>

			<br>

			<div class="field-group">
				<!-- Choose one specialty from the list -->
				<label for="specialty">Specialty Requirement:</label> <select
					id="specialty" name="specialty">
					<option value="">Select One</option>
					<option value="General">General</option>
					<option value="Medical">Medical</option>
					<option value="Surgical">Surgical</option>
					<option value="Maternity North">Maternity North</option>
					<option value="Maternity South">Maternity South</option>
					<option value="Gastro">Gastro</option>
					<option value="Birthing Unit">Birthing Unit</option>
				</select>
			</div>

			<br>

			<div class="field-group">
				<!-- Shift date should not be empty and should be a valid date  -->
				<label for="datepicker">Shift Date:</label> <input type="text"
					name="shiftDate" id="datepicker" placeholder=" MM/DD/YYYY" required>
			</div>

			<div class="field-group">
				<!-- Choose one shift from the list -->
				<label for="shift">Shift:</label> <select id="shift" name="shift"
					required>
					<option value="">Select One</option>
					<option value="AM">AM</option>
					<option value="M">M</option>
					<option value="PM">PM</option>
					<option value="T">T</option>
					<option value="N">N</option>
				</select>
			</div>

			<br>

			<div class="field-group">
				<!-- Choose one time from the list -->
				<label for="timefrom">Time From:</label> <select id="timefrom"
					name="timefrom" required>
					<option value="">Select One</option>
					<option value="07:00">07:00</option>
					<option value="15:00">15:00</option>
					<option value="19:00">19:00</option>
					<option value="23:00">23:00</option>
				</select>
			</div>

			<br>

			<div class="field-group">
				<!-- Choose one time to the list -->
				<label for="timeto">Time To:</label> <select id="timeto"
					name="timeto" required>
					<option value="">Select One</option>
					<option value="07:00">07:00</option>
					<option value="15:00">15:00</option>
					<option value="19:00">19:00</option>
					<option value="23:00">23:00</option>
				</select>
			</div>

			<div class="field-group">
				<!-- Quantity is a required field, entry must be numeric -->
				<label for="qty">Quantity:</label> <input type="text" name="qty"
					id="qty" size="5" maxlength="12" pattern="[1-9]{1,2}"
					title="Valid quantiy number only"
					placeholder="--Please enter quantity--" required />
			</div>

			<div class="field-group">
				<!-- Duty Manager ID should not be empty and should be numeric only -->
				<label for="dmid">Duty Manager ID:</label> <input type="text"
					name="dmid" id="dmid" size="5" maxlength="12"
					value="${dmid}" readonly />
			</div>

			<div class="field-group">
				<!-- Last name should not be empty and should be a string not a number -->
				<label for="email">DM Email:</label> <input type="text"
					name="email" id="email" size="10" maxlength="40"
					value ="${email}" readonly />
			</div>

			<div class="field-group">
				<!-- Request date must be filled -->
				<label for="reqdate">Request Date:</label> <input type="text"
					name="reqdate" id="reqdate" size="10" maxlength="40"
					value="<%= GlobalUtils.dateToStringWithoutQuotes(new java.util.Date())%>" readonly />
			</div>

		</fieldset>

		<input type="submit" value="Submit" />
	</form>
</body>
</html>